### ISSUE TITLE
Please check script ID and read permissions settings.

### ISSUE THREAD

**Issue by zvladru** [ta2gch/cheeriogs#2]
I have "You do not have access to library Cheerio, used by your script, or it has been deleted.", Please check script ID and read permissions settings.

**Comment by asciian** [comment]
Thank you for your report. Now I make it public at the following place. Please check it.

https://script.google.com/d/1ReeQ6WO8kKNxoaA_O0XEQ589cIrRvEBA9qcWpNqdOP17i47u6N9M5Xh0/edit?usp=sharing
